import { Header } from '@/components/pokemons/Header'
import { Button, Loading, ProgressBar } from '@carbon/react'
import { Add } from '@carbon/icons-react'
import Head from 'next/head'
import React from 'react'
import styles from '@/styles/pokemons.module.scss'

export const PokemonsPage: React.FC = () => {
  return (
    <>
      <Head>
        <title>Pokemons</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header />
        <div>
          Content
          <div>
            Hi there Dummy pokemons page
            <Button isExpressive>Hi there</Button>
            <Button kind="tertiary" isExpressive>
              Hi there
            </Button>
            <Button
              renderIcon={Add}
              iconDescription="Icon Description"
              hasIconOnly
              onClick={() => console.log('onClick')}
            />
            <Loading
              description="Active loading indicator"
              withOverlay={false}
            />
            <ProgressBar
              label="Progress bar label"
              helperText="Optional helper text"
              value={75}
            />
          </div>
        </div>
      </main>
    </>
  )
}

export default PokemonsPage
